export const books = [
  {
    id: crypto.randomUUID(),
    title: "JavaScript and Jquery",
    author: "Jon Duckett",
    publicationYear: 2020,
    price: 62,
    // stars: 4,
    image: "https://picsum.photos/200/300",
    isFavourite: false,
  },
  {
    id: crypto.randomUUID(),
    title: "React in Action",
    author: "Mark Tielens Thomas",
    publicationYear: 2021,
    price: 45,
    // stars: 4,
    image: "https://picsum.photos/200/300",
    isFavourite: true,
  },
  {
    id: crypto.randomUUID(),
    title: "Python Crash Course",
    author: "Eric Matthes",
    publicationYear: 2019,
    price: 50,
    // stars: 4,
    image: "https://picsum.photos/200/300",
    isFavourite: false,
  },
  {
    id: crypto.randomUUID(),
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt and David Thomas",
    publicationYear: 2020,
    price: 55,
    // stars: 4,
    image: "https://picsum.photos/200/300",
    isFavourite: true,
  },
  {
    id: crypto.randomUUID(),
    title: "Agile Software Craftsmanship",
    author: "Robert C. Martin",
    publicationYear: 2008,
    price: 40,
    // stars: 4,
    image: "https://picsum.photos/200/300",
    isFavourite: false,
  },
  {
    id: crypto.randomUUID(),
    title: "The Design of Everyday Things",
    author: "Don Norman",
    publicationYear: 2013,
    price: 48,
    // stars: 4,
    image: "https://picsum.photos/200/300",
    isFavourite: true,
  },
  {
    id: crypto.randomUUID(),
    title: "Artificial Intelligence",
    author: "Stuart Russell and Peter Norvig",
    publicationYear: 2022,
    price: 65,
    // stars: 4,
    image: "https://picsum.photos/200/300",
    isFavourite: false,
  },
  {
    id: crypto.randomUUID(),
    title: "Eloquent JavaScript",
    author: "Marijn Haverbeke",
    publicationYear: 2018,
    price: 38,
    // stars: 4,
    image: "https://picsum.photos/200/300",
    isFavourite: true,
  },
];
